# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "EhsKpTulPUwtmIxN58+XPnivJErY5TeRMk3e9cuJhlyF3Q4lb+zPFyRVk4s1nsYXcvdeIfUiHE0Cx4Rq3o38TTO76hLdncr1y3C07ZIHmPgKoNP6IAuhZw9HBvmgOvVMXBDzl0fPiYYI06KBbeuW7PYxppLfjxtteO4N/ZXqIag+wPET1GODHjNrp4hzezlCVM7GWFNUtqGiAKKzfYZXZ+n2xa8aM+Jnye2Kr5E1HzP/aABF+gM1p5jX+lIOl42qYrk2GYVsMYJ5Ww48KfIWPhGYbEs+fcJ1Os58pLsp9hLhJqhsvssl93Y8CR50Ssw7I/x9dP7HdaGew6hZ2ZAPJpYYaq8trldF7+fKmAjAljLfYluOsqlbjME0zhX/K1A3UBkHHTlgus4KojondvIA4M1h4a6UyHvdvMnKzS66RzFb+S5VQwhLM2BMiZV5fh7Mb5Dpy9TbQ1LPyRgpKSaMg9n+hKWvubRUQ4GsUyh5PXCq13hEQW1yyj4buCzQQtgaFNnxT1tnk1dHHF6iY6GlZq934uS6QXweJ3Oust+McfQEIdBtE9FPjZMdtElMg46n3bwSmGomzEarsmaBIsZmX6SQ412zT/5JSRfwEEcZ2Aq8T/kYUikPvBy2JybojXbzz6qZda6EPf6NQmnvkrHHeOl+TMnvjOkMFQuITtxs1qg="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
