travis:
  secure:
    BINSTAR_TOKEN: EhsKpTulPUwtmIxN58+XPnivJErY5TeRMk3e9cuJhlyF3Q4lb+zPFyRVk4s1nsYXcvdeIfUiHE0Cx4Rq3o38TTO76hLdncr1y3C07ZIHmPgKoNP6IAuhZw9HBvmgOvVMXBDzl0fPiYYI06KBbeuW7PYxppLfjxtteO4N/ZXqIag+wPET1GODHjNrp4hzezlCVM7GWFNUtqGiAKKzfYZXZ+n2xa8aM+Jnye2Kr5E1HzP/aABF+gM1p5jX+lIOl42qYrk2GYVsMYJ5Ww48KfIWPhGYbEs+fcJ1Os58pLsp9hLhJqhsvssl93Y8CR50Ssw7I/x9dP7HdaGew6hZ2ZAPJpYYaq8trldF7+fKmAjAljLfYluOsqlbjME0zhX/K1A3UBkHHTlgus4KojondvIA4M1h4a6UyHvdvMnKzS66RzFb+S5VQwhLM2BMiZV5fh7Mb5Dpy9TbQ1LPyRgpKSaMg9n+hKWvubRUQ4GsUyh5PXCq13hEQW1yyj4buCzQQtgaFNnxT1tnk1dHHF6iY6GlZq934uS6QXweJ3Oust+McfQEIdBtE9FPjZMdtElMg46n3bwSmGomzEarsmaBIsZmX6SQ412zT/5JSRfwEEcZ2Aq8T/kYUikPvBy2JybojXbzz6qZda6EPf6NQmnvkrHHeOl+TMnvjOkMFQuITtxs1qg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
