travis:
  secure:
    BINSTAR_TOKEN: dkrVwkrHlBepAro2yUcPJiqO5tVqL2RHIDSs1P/pH6ebGo/ZNSw9e3xk+8dV2FWdEldCGE9yMKd9DnFA99uQvh8lZksFlE9MdxdLgFE8zCERSSU8YXOyJmhHZn52XjGv0bC1u8haUxMgKRs1CbKA5B4chia+HBZFX6t/tqRlpN/yPMccawfQm3uEZPc+XYAe+mfoMOGUIoubn1ZBEUjdyHBR+PhF1bBOzh45HKZLRqeVfSqhg9CRUwLBAr6ZIWkIRk7GY4SswJv4Wejjec2JWjmVwcYnE0RJgMFnkqeTEulrvvwMpsJcMChrxfTDgm1cK04RHYAnTpuDySHYIcGVP7x6jvIkxVqQdvfpt9gqnYqu6RvZf/fbUAwP3t8tVL8J7RONyaUz9E+cizGSWCr8CO7aDXPnBr8/uY915/3KZS6kGS5V25TO7PLug0YH4e7b5eTBC7zTyvL00n8cUA199irohALPQxjIU8TUSj44rdwUbDRD0xsI3B2btISxKkiVz+YuCgYH0Ff3fd5fjBYLuWrmt+4ZH6RSQuI3wDthL7F0o2RY616vzjY+GJgPeCfIasfkVZ49s1qogkqBi8/ECy+sADFdILSo9XUFZWqHY5pYnpLMD1cTYwKrwFJb5x8Zm6egK5zXSb02saAkm8RRmBZ16r9f9sUwNEhHoS+YfnU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
