travis:
  secure:
    BINSTAR_TOKEN: ByLYm2zhHmZaZmGXIEGFWYpLkVQwY7Gs+3YK1E1Kd2zPWMOPCBu8EhAhG1e7LpnKRKa4VrN2wtWg2JNFoVgvWim8NIvHRqcE4Il+lyM2g1LZu8FNP/eDkocPkotVop5W5kK7dQtZoAL0uYmx8GD5+2rbZhAKYjZD1nTY0tZimacNMHZGdHmpKKQfxt7Jxrp6j1ZuPWIf/Ffx2JWcoP1Ta8JI8XJpsE+PmWolutKX5kDEJDAtp6WI/XNMG2iedJRxsqoWJPXTl/83qzY7OQl+8j/+IkPVu9OqtnQ4+vPLZ5zjB4+ZSb4wkbZNm0Yx8imyMn5VJ+wHkYFQuzb3qjIUhqcaFfcLjwQcrgr1sttWRCWFy+GFzmyJ77CAyYnHPZ59jSYFa/84IuycvQoD+aSuSD/iWIcF+xtzbhNOa0lk9eZYCj8sSoQOvfvvZG9xpiuxKCXb5TYFHoKxHnGvdVIQnKH6+rWoV5nH/yhmqrLLq+O3LZUOpRykSjq9MRfMt+kWf2QXOJ3UGEGJ4m54QVNnU9Vda2iwAywJVh820KFWvRmydz84QSOg9T56RsZUlHe6DtZFKBENh4fthGg2wMk8pYAW/Bn3hHgfvRrlX95p41meX5npz7DlC91fA+J0YryMIs/Ar0YstADAhTjj99nPfPn24VK7gZayoKNaoZhJNJg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
