travis:
  secure:
    BINSTAR_TOKEN: bDDOxMTuN4d0t5oeLOQg+3qdjYhnaO5YTOeX2YwiSRPm93D+Bysdtg6XNtnI8UrqmEMzPkyiYy0sSz0mPCPLUDpRaKr+lfRKc2ti1rUZzGPcRFCNg42UM5mKpPPpPL934JraqG6teurRzjaOv+yRmLb8EHaNRkWc3KK+2mC9qcA7a+X3g/aUYfz8S4jybzuMG1Ebihsvq3EthxfxvVJEw1n/O2uwxGf8EwT81gFZEJtgbLNcZhAs1f7Veg1O4vp7IGmgzWdDl/Shve0ZGldOlA0pwOTIWW0TwRySMxirAvJNA6JE+IfkfoIFUR88emA0N9G3F8rstei51VCmqpNvkPOZCo2lT9f6MBHyXO1fdRnQHVNrwElT5jXjMMcuIXoIIAaUGeHdKFnwXbVTIWh+LyzL8wS3zykPHaxD7KRcOOK1N4TuPOU7jXgJ8BxF6yfCjEeDkRaTGOYb4mewMJR5ikFVLO84g+6aHumoeSecphtheBdnwIpGNsa1jGMOGWI9fz6CzQv5TeafAPyPWbvXvzxi/03x+UmUjdoO4NsttI7h7ntQUEqFYAVCfZ+ObhqbPFc0XjQwjTbJcdvSBJ7jBz6GVOEw2rzUO9dLZUCuUwi/OSZ4uBuH4vUvTA7XzLEDrMqEMd2wwym8EG4xhrGerWGK7Dv9vaa5m1RdKyT8u+w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
